import re
from dataclasses import dataclass
from typing import Any, Protocol

from langchain_openai import ChatOpenAI

from app.config import GenerationSettings
from app.rag.context_builder import (
    PromptPackage,
)
from app.rag.post_generation_guardrails import (
    evaluate_post_generation_guardrails,
)


CITATION_PATTERN = re.compile(
    r"\[\s*SOURCE\s+(\d+)\s*\]",
    re.IGNORECASE,
)

SOURCES_SECTION_PATTERN = re.compile(
    r"(?im)"
    r"^\s*(?:#+\s*)?"
    r"sources\s*:?\s*$"
)

EXPLICIT_ABSTENTION_PATTERN = re.compile(
    r"^\s*"
    r"(?:\*\*)?"
    r"ABSTAIN"
    r"(?:\*\*)?"
    r"\s*:",
    re.IGNORECASE,
)


class ChatModelClient(Protocol):
    """
    Interface required by the generation service.
    """

    def invoke(
        self,
        input: Any,
        **kwargs: Any,
    ) -> Any:
        ...


@dataclass(frozen=True)
class AnswerValidation:
    """
    Result of basic source-label validation.
    """

    passed: bool

    citations_used: tuple[str, ...]
    unknown_citations: tuple[str, ...]

    has_sources_section: bool

    errors: tuple[str, ...]


@dataclass(frozen=True)
class GroundedAnswerResult:
    """
    Complete answer-generation and guardrail result.
    """

    answer: str
    raw_answer: str | None

    model_called: bool
    model_name: str

    abstained: bool

    citation_validation_passed: bool
    post_generation_guardrails_passed: bool

    citations_used: tuple[str, ...]

    claims_checked: int
    supported_claims: int

    validation_errors: tuple[str, ...]
    guardrail_errors: tuple[str, ...]

    input_tokens: int | None
    output_tokens: int | None
    total_tokens: int | None

    finish_reason: str | None


def build_generation_client(
    settings: GenerationSettings,
) -> ChatOpenAI:
    """
    Creates the LangChain OpenAI generation client.
    """

    client_arguments: dict[str, Any] = {
        "model": settings.model,
        "api_key": settings.api_key,
        "max_completion_tokens": (
            settings.max_output_tokens
        ),
        "timeout": settings.timeout_seconds,
        "max_retries": settings.max_retries,
        "use_responses_api": (
            settings.use_responses_api
        ),
    }

    if settings.temperature is not None:
        client_arguments["temperature"] = (
            settings.temperature
        )

    if settings.base_url is not None:
        client_arguments["base_url"] = (
            settings.base_url
        )

    return ChatOpenAI(
        **client_arguments
    )


def extract_response_text(
    response: Any,
) -> str:
    """
    Extracts text from a LangChain AI response.
    """

    response_text = getattr(
        response,
        "text",
        None,
    )

    if (
        isinstance(response_text, str)
        and response_text.strip()
    ):
        return response_text.strip()

    content = getattr(
        response,
        "content",
        None,
    )

    if isinstance(content, str):
        return content.strip()

    if isinstance(content, list):
        text_parts = []

        for block in content:
            if isinstance(block, str):
                text_parts.append(block)
                continue

            if isinstance(block, dict):
                block_text = block.get("text")

                if isinstance(block_text, str):
                    text_parts.append(
                        block_text
                    )

                continue

            block_text = getattr(
                block,
                "text",
                None,
            )

            if isinstance(block_text, str):
                text_parts.append(
                    block_text
                )

        return "\n".join(
            text_parts
        ).strip()

    return ""


def normalize_citation_label(
    citation_number: str,
) -> str:
    """
    Converts a matched source number to a standard
    label.
    """

    return f"SOURCE {int(citation_number)}"


def extract_citation_labels(
    answer: str,
) -> tuple[str, ...]:
    """
    Extracts unique source labels.
    """

    labels = {
        normalize_citation_label(
            citation_number
        )
        for citation_number
        in CITATION_PATTERN.findall(answer)
    }

    return tuple(
        sorted(
            labels,
            key=lambda label: int(
                label.split()[-1]
            ),
        )
    )


def normalize_generated_citations(
    answer: str,
    *,
    prompt_package: PromptPackage,
) -> str:
    """
    Converts known descriptive citations generated by
    the model into the required source-label format.

    Example:

    [Customer Identity Verification Policy
    (KYC-POL-2031, version 4.1, chunk 1/1)]

    becomes:

    [SOURCE 1]

    Only citation values supplied by the current prompt
    package are converted. Unknown bracketed content is
    not trusted or converted.
    """

    normalized_answer = answer

    citation_records = sorted(
        prompt_package.citations,
        key=lambda record: len(
            record.citation
        ),
        reverse=True,
    )

    for citation_record in citation_records:
        descriptive_citation = (
            citation_record.citation.strip()
        )

        if not descriptive_citation:
            continue

        descriptive_pattern = re.compile(
            r"\[\s*"
            + re.escape(
                descriptive_citation
            )
            + r"\s*\]",
            re.IGNORECASE,
        )

        normalized_answer = (
            descriptive_pattern.sub(
                f"[{citation_record.label}]",
                normalized_answer,
            )
        )

    return normalized_answer.strip()


def split_answer_sections(
    answer: str,
) -> tuple[str, str]:
    """
    Splits a generated response into the answer body
    and final Sources section.
    """

    match = SOURCES_SECTION_PATTERN.search(
        answer
    )

    if match is None:
        return answer.strip(), ""

    answer_body = answer[
        :match.start()
    ].strip()

    sources_section = answer[
        match.end():
    ].strip()

    return (
        answer_body,
        sources_section,
    )


def is_explicit_abstention(
    answer: str,
) -> bool:
    """
    Returns True when the model deliberately follows
    the ABSTAIN response contract.
    """

    return bool(
        EXPLICIT_ABSTENTION_PATTERN.match(
            answer
        )
    )


def validate_generated_answer(
    answer: str,
    *,
    prompt_package: PromptPackage,
) -> AnswerValidation:
    """
    Performs basic citation-label validation.

    Only citations in the answer body are treated as
    citations used by the generated answer.
    """

    errors = []

    (
        answer_body,
        sources_section,
    ) = split_answer_sections(answer)

    citations_used = extract_citation_labels(
        answer_body
    )

    sources_section_citations = (
        extract_citation_labels(
            sources_section
        )
    )

    allowed_citations = {
        citation.label.upper()
        for citation
        in prompt_package.citations
    }

    all_generated_citations = set(
        citations_used
    ) | set(
        sources_section_citations
    )

    unknown_citations = tuple(
        sorted(
            citation
            for citation
            in all_generated_citations
            if citation not in allowed_citations
        )
    )

    has_sources_section = bool(
        SOURCES_SECTION_PATTERN.search(
            answer
        )
    )

    if unknown_citations:
        errors.append(
            "The answer contains source labels that "
            "were not supplied in the prompt: "
            + ", ".join(unknown_citations)
        )

    if (
        prompt_package.evidence_count > 0
        and not citations_used
    ):
        errors.append(
            "The answer body does not contain any "
            "source citation labels."
        )

    if (
        prompt_package.evidence_count > 0
        and not has_sources_section
    ):
        errors.append(
            "The answer does not contain a Sources "
            "section."
        )

    if has_sources_section:
        missing_source_entries = [
            citation
            for citation in citations_used
            if citation
            not in sources_section_citations
        ]

        if missing_source_entries:
            errors.append(
                "The Sources section is missing labels "
                "used in the answer body: "
                + ", ".join(
                    missing_source_entries
                )
            )

        unused_source_entries = [
            citation
            for citation
            in sources_section_citations
            if citation not in citations_used
        ]

        if unused_source_entries:
            errors.append(
                "The Sources section contains labels "
                "that were not cited in the answer "
                "body: "
                + ", ".join(
                    unused_source_entries
                )
            )

    return AnswerValidation(
        passed=not errors,
        citations_used=citations_used,
        unknown_citations=(
            unknown_citations
        ),
        has_sources_section=(
            has_sources_section
        ),
        errors=tuple(errors),
    )


def build_no_evidence_answer() -> str:
    """
    Returns a deterministic no-evidence response.
    """

    return (
        "I cannot confirm this from the available "
        "authorized policy evidence. The request may "
        "require an authorized transactional system, "
        "policy owner, compliance team, or authorized "
        "reviewer.\n\n"
        "Sources:\n"
        "No policy sources were used."
    )


def build_validation_failure_answer() -> str:
    """
    Returns a controlled citation-validation failure
    response.
    """

    return (
        "I cannot provide a verified answer because the "
        "generated response did not pass source citation "
        "validation. Please consult the relevant policy "
        "owner, compliance team, or an authorized "
        "reviewer.\n\n"
        "Sources:\n"
        "No validated answer was returned."
    )


def build_guardrail_failure_answer() -> str:
    """
    Returns a controlled post-generation guardrail
    failure response.
    """

    return (
        "I cannot provide a verified answer because the "
        "generated response did not pass grounding and "
        "safety checks. Please consult the relevant "
        "policy owner, compliance team, or an authorized "
        "reviewer.\n\n"
        "Sources:\n"
        "No guardrail-approved answer was returned."
    )


def get_usage_value(
    usage_metadata: dict[str, Any],
    key: str,
) -> int | None:
    """
    Safely reads a token-usage value.
    """

    value = usage_metadata.get(key)

    if isinstance(value, int):
        return value

    return None


class GroundedAnswerGenerationService:
    """
    Generates an answer and applies validation.

    Layer 1:
    Basic citation-label validation.

    Layer 2:
    Claim grounding, number verification,
    Sources-section integrity, secret detection,
    PII detection, and instruction-leakage detection.

    Explicit ABSTAIN responses are converted into a
    deterministic, citation-free public abstention.
    """

    def __init__(
        self,
        *,
        chat_model: ChatModelClient,
        settings: GenerationSettings,
    ) -> None:
        self.chat_model = chat_model
        self.settings = settings

    def generate(
        self,
        prompt_package: PromptPackage,
    ) -> GroundedAnswerResult:
        """
        Generates one guarded answer.
        """

        if prompt_package.should_abstain:
            return GroundedAnswerResult(
                answer=build_no_evidence_answer(),
                raw_answer=None,
                model_called=False,
                model_name=self.settings.model,
                abstained=True,
                citation_validation_passed=True,
                post_generation_guardrails_passed=True,
                citations_used=(),
                claims_checked=0,
                supported_claims=0,
                validation_errors=(),
                guardrail_errors=(),
                input_tokens=None,
                output_tokens=None,
                total_tokens=None,
                finish_reason=None,
            )

        messages = [
            (
                "system",
                prompt_package.system_prompt,
            ),
            (
                "human",
                prompt_package.user_prompt,
            ),
        ]

        response = self.chat_model.invoke(
            messages
        )

        raw_answer = extract_response_text(
            response
        )

        if not raw_answer:
            raise RuntimeError(
                "The generation model returned an "
                "empty answer."
            )

        normalized_answer = (
            normalize_generated_citations(
                raw_answer,
                prompt_package=prompt_package,
            )
        )

        additional_kwargs = getattr(
            response,
            "additional_kwargs",
            {},
        ) or {}

        refusal = additional_kwargs.get(
            "refusal"
        )

        if refusal:
            raise RuntimeError(
                "The generation model refused the "
                f"request: {refusal}"
            )

        usage_metadata = getattr(
            response,
            "usage_metadata",
            {},
        ) or {}

        response_metadata = getattr(
            response,
            "response_metadata",
            {},
        ) or {}

        model_name = str(
            response_metadata.get(
                "model_name",
                self.settings.model,
            )
        )

        finish_reason_value = (
            response_metadata.get(
                "finish_reason"
            )
        )

        finish_reason = (
            str(finish_reason_value)
            if finish_reason_value is not None
            else None
        )

        input_tokens = get_usage_value(
            usage_metadata,
            "input_tokens",
        )

        output_tokens = get_usage_value(
            usage_metadata,
            "output_tokens",
        )

        total_tokens = get_usage_value(
            usage_metadata,
            "total_tokens",
        )

        if is_explicit_abstention(
            normalized_answer
        ):
            return GroundedAnswerResult(
                answer=build_no_evidence_answer(),
                raw_answer=raw_answer,
                model_called=True,
                model_name=model_name,
                abstained=True,
                citation_validation_passed=True,
                post_generation_guardrails_passed=True,
                citations_used=(),
                claims_checked=0,
                supported_claims=0,
                validation_errors=(),
                guardrail_errors=(),
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
                finish_reason=finish_reason,
            )

        citation_validation = (
            validate_generated_answer(
                normalized_answer,
                prompt_package=prompt_package,
            )
        )

        if not citation_validation.passed:
            return GroundedAnswerResult(
                answer=(
                    build_validation_failure_answer()
                ),
                raw_answer=raw_answer,
                model_called=True,
                model_name=model_name,
                abstained=True,
                citation_validation_passed=False,
                post_generation_guardrails_passed=False,
                citations_used=(),
                claims_checked=0,
                supported_claims=0,
                validation_errors=(
                    citation_validation.errors
                ),
                guardrail_errors=(),
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
                finish_reason=finish_reason,
            )

        guardrail_result = (
            evaluate_post_generation_guardrails(
                normalized_answer,
                prompt_package=prompt_package,
            )
        )

        if not guardrail_result.passed:
            return GroundedAnswerResult(
                answer=(
                    build_guardrail_failure_answer()
                ),
                raw_answer=raw_answer,
                model_called=True,
                model_name=model_name,
                abstained=True,
                citation_validation_passed=True,
                post_generation_guardrails_passed=False,
                citations_used=(),
                claims_checked=(
                    guardrail_result.claims_checked
                ),
                supported_claims=(
                    guardrail_result.supported_claims
                ),
                validation_errors=(),
                guardrail_errors=(
                    guardrail_result.errors
                ),
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
                finish_reason=finish_reason,
            )

        return GroundedAnswerResult(
            answer=normalized_answer,
            raw_answer=raw_answer,
            model_called=True,
            model_name=model_name,
            abstained=False,
            citation_validation_passed=True,
            post_generation_guardrails_passed=True,
            citations_used=(
                citation_validation.citations_used
            ),
            claims_checked=(
                guardrail_result.claims_checked
            ),
            supported_claims=(
                guardrail_result.supported_claims
            ),
            validation_errors=(),
            guardrail_errors=(),
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=total_tokens,
            finish_reason=finish_reason,
        )