from __future__ import annotations

from getpass import getpass
from pathlib import Path
from urllib.parse import quote

from dotenv import dotenv_values


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ENV_PATH = PROJECT_ROOT / "backend" / ".env"
TARGET_ENV_PATH = PROJECT_ROOT / ".env.docker"
SECRET_DIRECTORY = PROJECT_ROOT / ".docker-secrets"
POSTGRES_SECRET_PATH = (
    SECRET_DIRECTORY / "postgres_password"
)

CONTAINER_OVERRIDDEN_KEYS = {
    "APP_ENVIRONMENT",
    "API_CORS_ORIGINS",
    "CACHE_ENABLED",
    "DATABASE_APPLICATION_NAME",
    "DATABASE_AUTO_CREATE_SCHEMA",
    "DATABASE_URL",
    "OTEL_ENABLED",
    "REDIS_URL",
}

GENERATED_KEYS = {
    "BUILD_INDEX_ON_STARTUP",
    "FORCE_REBUILD_INDEX",
    "NEXT_PUBLIC_API_BASE_URL",
    "POSTGRES_DB",
    "POSTGRES_PASSWORD_URL",
    "POSTGRES_USER",
}


def contains_host_only_path(
    value: str,
) -> bool:
    """
    Prevents macOS absolute paths from being copied
    into the Linux container environment.
    """

    normalized = value.strip()

    return (
        normalized.startswith("/Users/")
        or ":///Users/" in normalized
        or normalized.startswith(
            "/private/var/"
        )
    )


def render_env_value(
    value: str,
) -> str:
    """
    Renders a value using double quotes when needed.
    """

    if "\n" in value or "\r" in value:
        raise RuntimeError(
            "Environment values cannot contain newlines."
        )

    special_characters = {
        " ",
        "#",
        "$",
        '"',
        "'",
    }

    if not any(
        character in value
        for character in special_characters
    ):
        return value

    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "$$")
    )

    return f'"{escaped}"'


def load_source_values() -> dict[str, str]:
    if not SOURCE_ENV_PATH.exists():
        raise FileNotFoundError(
            "backend/.env was not found. Create the "
            "backend environment file before preparing "
            "the Docker environment."
        )

    loaded_values = dotenv_values(
        SOURCE_ENV_PATH
    )

    copied_values: dict[str, str] = {}

    for key, raw_value in loaded_values.items():
        if raw_value is None:
            continue

        if (
            key in CONTAINER_OVERRIDDEN_KEYS
            or key in GENERATED_KEYS
        ):
            continue

        value = raw_value.strip()

        if not value:
            continue

        if contains_host_only_path(value):
            print(
                f"Skipping host-only path setting: {key}"
            )
            continue

        copied_values[key] = value

    return copied_values


def read_postgres_password() -> str:
    first_password = getpass(
        "Choose a PostgreSQL password for Docker: "
    )

    second_password = getpass(
        "Enter the same password again: "
    )

    if not first_password:
        raise RuntimeError(
            "The PostgreSQL password cannot be empty."
        )

    if first_password != second_password:
        raise RuntimeError(
            "The two PostgreSQL passwords did not match."
        )

    if "\n" in first_password or "\r" in first_password:
        raise RuntimeError(
            "The PostgreSQL password cannot contain "
            "newlines."
        )

    return first_password


def write_secret(
    password: str,
) -> None:
    SECRET_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    POSTGRES_SECRET_PATH.write_text(
        password,
        encoding="utf-8",
    )

    POSTGRES_SECRET_PATH.chmod(
        0o600
    )


def write_docker_environment(
    *,
    source_values: dict[str, str],
    password: str,
) -> None:
    values = dict(source_values)

    values.update(
        {
            "POSTGRES_DB": "policy_copilot",
            "POSTGRES_USER": "policy_copilot",
            "POSTGRES_PASSWORD_URL": quote(
                password,
                safe="",
            ),
            "NEXT_PUBLIC_API_BASE_URL": (
                "http://127.0.0.1:8000/api/v1"
            ),
            "BUILD_INDEX_ON_STARTUP": "true",
            "FORCE_REBUILD_INDEX": "false",
        }
    )

    rendered_lines = [
        "# Generated by scripts/prepare_docker_env.py",
        "# Do not commit this file.",
        "",
    ]

    rendered_lines.extend(
        f"{key}={render_env_value(value)}"
        for key, value in sorted(
            values.items()
        )
    )

    TARGET_ENV_PATH.write_text(
        "\n".join(rendered_lines) + "\n",
        encoding="utf-8",
    )

    TARGET_ENV_PATH.chmod(
        0o600
    )


def main() -> None:
    source_values = load_source_values()
    password = read_postgres_password()

    write_secret(password)

    write_docker_environment(
        source_values=source_values,
        password=password,
    )

    print()
    print(
        f"Created: {TARGET_ENV_PATH}"
    )
    print(
        f"Created: {POSTGRES_SECRET_PATH}"
    )
    print(
        "The raw PostgreSQL password is stored only "
        "in the local Docker secret file."
    )


if __name__ == "__main__":
    main()
